### ISSUE TITLE
Frontend: Query returns FileNotFoundError: [Errno 2] No such file or directory: '../data/qgmivsTvSXw_churchbell.mp3'

### ISSUE THREAD

**Issue by alexcg1** [akshatdalton/Audrch#3]
Indexing default dataset is working fine, but when I query with one of the mp3s in the dataset I'm getting issues:

## Streamlit frontend error output

![image](https://user-images.githubusercontent.com/4182659/149350424-c52178d5-8b72-4835-a25d-299f8a744dc3.png)

```
2022-01-13 14:37:45.598 Traceback (most recent call last):
  File "/mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/mnt/data/work/repos/community/Audrch/client/app.py", line 19, in <module>
    st.audio(f"../{match['uri']}")
  File "/mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/streamlit/elements/media.py", line 59, in audio
    marshall_audio(coordinates, audio_proto, data, format, start_time)
  File "/mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/streamlit/elements/media.py", line 246, in marshall_audio
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "/mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/streamlit/elements/media.py", line 157, in _marshall_av_media
    with open(data, "rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '../data/qgmivsTvSXw_churchbell.mp3'
```

No error output from backend, so I guess it's a Streamlit thing?

## Backend output

For reference, here's what showed after running `app.py`:

```        encoder@728194[I]:2022-01-13 14:36:46.768861: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
        encoder@728194[I]:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
        encoder@728194[I]:2022-01-13 14:36:47.185705: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 201326592 exceeds 10% of free system memory.
        encoder@728194[I]:        encoder@ 1[L]: Executor VggishAudioEncoder started
UserWarning: ignored unknown argument: ['45678']. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/jina/helper.py:685)
1 docs =  DocumentArray has 8 items (showing first three):
{'id': '392ba358-747e-11ec-bd4e-dc1ba1a7eaa4', 'uri': 'data/HL-SGox-Ez0_churchbell.mp3', 'mime_type': 'audio/mpeg'},
{'id': '392c0d16-747e-11ec-bd4e-dc1ba1a7eaa4', 'uri': 'data/qgmivsTvSXw_churchbell.mp3', 'mime_type': 'audio/mpeg'},
{'id': '392c0f00-747e-11ec-bd4e-dc1ba1a7eaa4', 'uri': 'data/LX_FgjpJE60_airplane.mp3', 'mime_type': 'audio/mpeg'}
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
        encoder@728194[I]:2022-01-13 14:36:53.031128: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 150994944 exceeds 10% of free system memory.
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
        encoder@728194[I]:2022-01-13 14:36:58.779066: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 150994944 exceeds 10% of free system memory.
data/HL-SGox-Ez0_churchbell.mp3, 3
+- data/HL-SGox-Ez0_churchbell.mp3: 0.000000, {'beg_in_ms': 0.0, 'end_in_ms': 4000.0}
+- data/IusuWEAoIoY_churchbell.mp3: 0.002978, {'beg_in_ms': 0.0, 'end_in_ms': 4000.0}
+- data/_JTHtcRHxnw_churchbell.mp3: 0.003295, {'beg_in_ms': 4000.0, 'end_in_ms': 8000.0}
data/qgmivsTvSXw_churchbell.mp3, 3
+- data/qgmivsTvSXw_churchbell.mp3: 0.000000, {'end_in_ms': 6000.0, 'beg_in_ms': 2000.0}
+- data/kjRaoBHgWXQ_airplane.mp3: 0.000028, {'beg_in_ms': 0.0, 'end_in_ms': 4000.0}
+- data/YpUQ46pPj4c_airplane.mp3: 0.000029, {'end_in_ms': 8000.0, 'beg_in_ms': 4000.0}
+- data/LX_FgjpJE60_airplane.mp3: 0.000034, {'end_in_ms': 8000.0, 'beg_in_ms': 4000.0}
data/LX_FgjpJE60_airplane.mp3, 3
+- data/LX_FgjpJE60_airplane.mp3: 0.000000, {'beg_in_ms': 0.0, 'end_in_ms': 4000.0}
+- data/kjRaoBHgWXQ_airplane.mp3: 0.000006, {'end_in_ms': 8000.0, 'beg_in_ms': 4000.0}
+- data/6pO06krKrf8_30000_airplane.mp3: 0.000007, {'end_in_ms': 4000.0, 'beg_in_ms': 0.0}
+- data/YpUQ46pPj4c_airplane.mp3: 0.000008, {'beg_in_ms': 4000.0, 'end_in_ms': 8000.0}
data/6pO06krKrf8_30000_airplane.mp3, 3
+- data/6pO06krKrf8_30000_airplane.mp3: 0.000000, {'end_in_ms': 4000.0, 'beg_in_ms': 0.0}
+- data/LX_FgjpJE60_airplane.mp3: 0.000007, {'beg_in_ms': 2000.0, 'end_in_ms': 6000.0}
+- data/kjRaoBHgWXQ_airplane.mp3: 0.000008, {'end_in_ms': 8000.0, 'beg_in_ms': 4000.0}
data/kjRaoBHgWXQ_airplane.mp3, 3
+- data/kjRaoBHgWXQ_airplane.mp3: 0.000000, {'end_in_ms': 4000.0, 'beg_in_ms': 0.0}
+- data/LX_FgjpJE60_airplane.mp3: 0.000006, {'beg_in_ms': 0.0, 'end_in_ms': 4000.0}
+- data/6pO06krKrf8_30000_airplane.mp3: 0.000009, {'beg_in_ms': 2000.0, 'end_in_ms': 6000.0}
data/IusuWEAoIoY_churchbell.mp3, 3
+- data/IusuWEAoIoY_churchbell.mp3: 0.000000, {'beg_in_ms': 2000.0, 'end_in_ms': 6000.0}
+- data/_JTHtcRHxnw_churchbell.mp3: 0.000043, {'beg_in_ms': 2000.0, 'end_in_ms': 6000.0}
data/_JTHtcRHxnw_churchbell.mp3, 3
+- data/_JTHtcRHxnw_churchbell.mp3: 0.000000, {'end_in_ms': 4000.0, 'beg_in_ms': 0.0}
+- data/IusuWEAoIoY_churchbell.mp3: 0.000043, {'end_in_ms': 8000.0, 'beg_in_ms': 4000.0}
data/YpUQ46pPj4c_airplane.mp3, 3
+- data/YpUQ46pPj4c_airplane.mp3: 0.000000, {'end_in_ms': 4000.0, 'beg_in_ms': 0.0}
+- data/LX_FgjpJE60_airplane.mp3: 0.000008, {'beg_in_ms': 2000.0, 'end_in_ms': 6000.0}
+- data/6pO06krKrf8_30000_airplane.mp3: 0.000011, {'end_in_ms': 6000.0, 'beg_in_ms': 2000.0}
UserWarning: PySoundFile failed. Trying audioread instead. (raised from /mnt/data/work/repos/community/Audrch/env/lib/python3.7/site-packages/librosa/core/audio.py:165)
```

As mentioned, no error output. Backend output stayed exactly same pre-query and post-query

**Comment by akshatdalton** [comment]
> No error output from backend, so I guess it's a Streamlit thing?

Probably, yes and after seeing: `FileNotFoundError: [Errno 2] No such file or directory: '../data/qgmivsTvSXw_churchbell.mp3'`, one of the possible reasons could be that I am using [relative path](https://github.com/akshatdalton/Audrch/blob/72b6b7e68ef5df59c3cbbe26a1844bd68166ccc1/client/app.py#L19) to find the file and it is throwing some issues over here.

**Comment by akshatdalton** [comment]
@alexcg1, I have pushed new changes, can you try now?

**Comment by alexcg1** [comment]
Sure thing

**Comment by alexcg1** [comment]
Nice, it works perfectly now! I'll close the issue
